# Generated by Django 5.0.4 on 2024-04-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0002_alter_bugreport_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Very Urgent'), (2, 'Urgent'), (3, 'Normal'), (4, 'Not Urgent'), (5, 'Very Not Urgent')], default='Normal'),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Very Urgent'), (2, 'Urgent'), (3, 'Normal'), (4, 'Not Urgent'), (5, 'Very Not Urgent')], default='Normal'),
        ),
    ]
