# Generated by Django 5.0.4 on 2024-04-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0003_alter_bugreport_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='priority',
            field=models.IntegerField(choices=[('Very Urgent', 1), ('Urgent', 2), ('Normal', 3), ('Not Urgent', 4), ('Very Not Urgent', 5)], default=3),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='priority',
            field=models.IntegerField(choices=[('Very Urgent', 1), ('Urgent', 2), ('Normal', 3), ('Not Urgent', 4), ('Very Not Urgent', 5)], default=3),
        ),
    ]
