# Generated by Django 5.0.4 on 2024-04-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0005_alter_bugreport_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='status',
        ),
        migrations.AddField(
            model_name='bugreport',
            name='status',
            field=models.ManyToManyField(choices=[('New', 'Новая'), ('In_progress', 'В работе'), ('Completed', 'Завершена')], default='New', max_length=50, to='quality_control.bugreport'),
        ),
    ]
