# Generated by Django 5.0.4 on 2024-04-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0006_remove_bugreport_status_bugreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='status',
            field=models.ManyToManyField(choices=[(1, 'Рассмотрение'), (2, 'Принято'), (3, 'Отклонено')], to='quality_control.bugreport'),
        ),
    ]
