# Generated by Django 5.0.4 on 2024-04-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0007_alter_bugreport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='status',
        ),
        migrations.AddField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('Consideration', 'Рассмотрение'), ('Accepted', 'Принято'), ('Rejected', 'Отклонено')], default='Сonsideration', max_length=50),
        ),
    ]
